server:
  port: 8051
  max-http-header-size: 20480
  
spring:
  application:
    name: DEMO-CLIENT
  mvc:
    throw-exception-if-no-handler-found: true
  zipkin:
    #base-url:当你设置sleuth-cli收集信息后通过http传输到zinkin-server时，需要在这里配置
    base-url: http://106.12.16.45:9411
    enabled: true
  sleuth:
    sampler:
      #收集追踪信息的比率，如果是0.1则表示只记录10%的追踪数据，如果要全部追踪，设置为1（实际场景不推荐，因为会造成不小的性能消耗）
      probability: 1
  cloud:
    inetutils: 
      preferred-networks: 0.0.0.0

eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
    ip-address: 106.12.16.45
  client:
    serviceUrl:
      defaultZone: http://eureka.hperson.com/eureka/
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
    
      
